language: python
python:
  - "2.7"

services: mongodb

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests tests/test_alerts.py tests/test_auth.py tests/test_heartbeats.py tests/test_metrics.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_alerta_bea897ab84_4
  - python -m properform Push 47.88.50.110:15554 asdf_alerta_bea897ab84_4 ./profile_alerta_bea897ab84_4



 #2017-08-13 11:12:28 modified at 0 #2017-08-13 11:12:32 modified at 1 #2017-08-13 11:12:37 modified at 2 #2017-08-13 11:12:41 modified at 3 #2017-08-13 11:12:46 modified at 4