language: python
python:
  - "2.7"

services: mongodb


addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server


before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq



# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests tests/test_alerts.py tests/test_auth.py tests/test_heartbeats.py tests/test_metrics.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_alerta_1e75234901_4
  - python -m properform Push 47.88.50.110:15554 asdf_alerta_1e75234901_4 ./profile_alerta_1e75234901_4



 #2017-08-13 10:46:20 modified at 0 #2017-08-13 10:46:24 modified at 1 #2017-08-13 10:46:29 modified at 2 #2017-08-13 10:46:33 modified at 3 #2017-08-13 10:46:38 modified at 4