language: python
python:
  - "2.7"




services: mongodb

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform

# command to run tests
script: 
  - nosetests tests/test_alerts.py tests/test_auth.py tests/test_heartbeats.py --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_alerta_561333823e_2
  - python -m properform Push 47.88.50.110:15554 asdf_alerta_561333823e_2 ./profile_alerta_561333823e_2



 #2017-08-13 11:37:02 modified at 0 #2017-08-13 11:37:06 modified at 1 #2017-08-13 11:37:10 modified at 2