language: python
python:
  - "2.7"


services: mongodb


addons:
  apt:
    sources:
    - mongodb-3.0-precise
    packages:
    - mongodb-org-server

before_install:
   # add for profile
  - sudo add-apt-repository -y ppa:ubuntu-toolchain-r/test
  - sudo apt-get update -qq


# command to install dependencies
install:
  - "pip install ."
  - "pip install -r requirements.txt"
# add for profile
  - sudo apt-get install -qq g++-4.8
  - export CXX="g++-4.8"
  - pip install nose-cprof
  - pip install properform


# command to run tests
script: 
  - nosetests tests/* --with-cprofile --cprofile-stats-erase --cprofile-stats-file=profile_alerta_6d7fe45d94_2
  - python -m properform Push 47.88.50.110:15554 asdf_alerta_6d7fe45d94_2 ./profile_alerta_6d7fe45d94_2



 #2017-08-13 10:06:21 modified at 0 #2017-08-13 10:06:26 modified at 1 #2017-08-13 10:06:30 modified at 2